# Generated by Django 4.1.7 on 2024-02-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhoenixBlog', '0005_category_created_at_category_parent_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoenixBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
